name: MenaProtection
main: MenaProtection\Main
version: 1.0.0
api: 5.0.0
author: TuNombre
description: Plugin de protecci칩n de 치reas usando bloques Mena
website: https://github.com/tunombre/MenaProtection

permissions:
  menaprotection.admin:
    description: Permite usar comandos de administraci칩n de MenaProtection
    default: op
  menaprotection.give:
    description: Permite dar bloques Mena a otros jugadores
    default: op
  menaprotection.bypass:
    description: Permite construir en 치reas protegidas
    default: op 